/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package auction.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author dell.com
 */
public class additem extends javax.swing.JFrame {
Connection con;
ResultSet rs;
PreparedStatement ps;

  
    public additem() {
        initComponents();
        try
        {
        String driver= "sun.jdbc.odbc.JdbcOdbcDriver";
        Class.forName(driver);
        String auction= "jdbc:odbc:auction";
        con=DriverManager.getConnection(auction);
        
        }
        catch(Exception e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        e = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        a = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setText("ADD ITEM FOR AUCTION");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 50, 450, 29);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("ADD ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 380, 150, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel10.setText("ITEM NAME");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(190, 160, 120, 20);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel18.setText("SURNAME");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(190, 200, 100, 30);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel19.setText("STARTING BID");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(190, 280, 120, 40);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel21.setText("COST (per piece)");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(190, 230, 160, 50);

        e.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        e.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(e);
        e.setBounds(450, 280, 190, 30);

        c.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        c.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(c);
        c.setBounds(450, 240, 190, 30);

        b.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        b.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(b);
        b.setBounds(450, 200, 190, 30);

        a.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        a.setForeground(new java.awt.Color(51, 51, 51));
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(450, 160, 190, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String a1=a.getText();
        String a2=b.getText();
        String a4=c.getText();
        String a6=e.getText();
        String a7=e.getText();
       try
        {
                ps= con.prepareStatement("insert into DETAILS(item,np,cost,sb,HB)");
                ps.setString(1, a1);
                ps.setString(2, a2);
                ps.setString(3, a4);
                ps.setString(4, a6);
                ps.setString(5, a7);
               
                ps.executeQuery();
                JOptionPane.showMessageDialog(null," ITEM ADDED ");
                new welcome().setVisible(true);
            }
            
         catch(Exception e){}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(additem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(additem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(additem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(additem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new additem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField c;
    private javax.swing.JTextField e;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    // End of variables declaration//GEN-END:variables
}
