/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package auction.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author dell.com
 */
public class register extends javax.swing.JFrame {
Connection con;
ResultSet rs;
PreparedStatement ps;

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
         try
        {
        String driver= "sun.jdbc.odbc.JdbcOdbcDriver";
        Class.forName(driver);
        String auction= "jdbc:odbc:auction";
        con=DriverManager.getConnection(auction);
        
        }
        catch(Exception e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        h = new javax.swing.JPasswordField();
        i = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        g = new javax.swing.JTextField();
        e = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        a = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setText("REGISTER HERE....");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 40, 360, 29);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 440, 150, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel10.setText("FIRST NAME");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(160, 130, 110, 20);

        h.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        h.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(h);
        h.setBounds(420, 320, 190, 28);

        i.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        i.setForeground(new java.awt.Color(51, 51, 51));
        i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iActionPerformed(evt);
            }
        });
        getContentPane().add(i);
        i.setBounds(420, 360, 190, 28);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel18.setText("SURNAME");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(160, 170, 100, 30);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel19.setText("CONTACT NO.");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(160, 240, 120, 40);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel20.setText("USER ID");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(160, 280, 100, 40);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel21.setText("D.O.B.");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(160, 200, 60, 50);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel22.setText("PASSWORD");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(160, 330, 120, 30);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel23.setText("CONFIRM PASSWORD");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(160, 370, 180, 22);

        g.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        g.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(g);
        g.setBounds(420, 280, 190, 30);

        e.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        e.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(e);
        e.setBounds(420, 240, 190, 30);

        c.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        c.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(c);
        c.setBounds(420, 200, 190, 30);

        b.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        b.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(b);
        b.setBounds(420, 160, 190, 30);

        a.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        a.setForeground(new java.awt.Color(51, 51, 51));
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(420, 120, 190, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String a1=a.getText();
        String a2=b.getText();
        String a4=c.getText();
        String a6=e.getText();
        String a7=g.getText();
        String a8=h.getText();
        String a9=i.getText();
        try
        {
            if(a8 ==a9)
            {
                ps= con.prepareStatement("insert into register(fname,sname,dob,cno,username,password)");
                ps.setString(1, a1);
                ps.setString(2, a2);
               
                ps.setString(3, a4);
             
                ps.setString(4, a6);
                ps.setString(5, a8);
                ps.executeQuery();
                JOptionPane.showMessageDialog(null," USER REGISTERED ");
                new login().setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Username already exist or confirm your password again");
                new register().setVisible(true);
            }

        }
        catch(Exception e){}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField c;
    private javax.swing.JTextField e;
    private javax.swing.JTextField g;
    private javax.swing.JPasswordField h;
    private javax.swing.JPasswordField i;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    // End of variables declaration//GEN-END:variables
}
