/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author dell.com
 */
public class LEAVE extends javax.swing.JFrame {

    Connection con;
    ResultSet rs;
    PreparedStatement ps;
    /**
     * Creates new form LEAVE
     */
    public LEAVE() {
        initComponents();
        try
        {
        String driver= "sun.jdbc.odbc.JdbcOdbcDriver";
        Class.forName(driver);
        String leave= "jdbc:odbc:empl_leave";
        con=DriverManager.getConnection(leave);
        
        }
        catch(Exception e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        c = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        d = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        b = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        e = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(590, 510));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("LEAVE FORM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 40, 203, 28);

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("FROM/ON");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 150, 90, 14);
        getContentPane().add(a);
        a.setBounds(340, 150, 194, 20);

        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("TYPE OF LEAVE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 270, 90, 14);

        c.setForeground(new java.awt.Color(0, 0, 255));
        c.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sick", "Casual", "Earned", "Sectional", "Maternity", "Study", "Paternity", "Transfer" }));
        getContentPane().add(c);
        c.setBounds(340, 260, 93, 20);

        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("APPLY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 430, 177, 23);

        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("REASON");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 350, 50, 14);

        d.setColumns(20);
        d.setRows(5);
        jScrollPane1.setViewportView(d);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(340, 310, 200, 96);

        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("TO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 190, 30, 14);
        getContentPane().add(b);
        b.setBounds(340, 190, 194, 20);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(0, 230, 590, 10);
        getContentPane().add(e);
        e.setBounds(340, 110, 194, 20);

        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("USERNAME");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 110, 90, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String a2=a.getText();
      String a3=b.getText();
      String a4=(String)c.getSelectedItem( );
      String a5=d.getText();
      String a1=e.getText();
      try{
      ps= con.prepareStatement("insert into applyleave(username,from/on,to,type,reason)");
          ps.setString(1, a1);
          ps.setString(2, a2);
          ps.setString(3, a3);
          ps.setString(4, a4);
           ps.executeQuery();
          JOptionPane.showMessageDialog(null," Leave Submited ");
            new LOGIN().setVisible(true);
      }
      catch(Exception e){};
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LEAVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LEAVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LEAVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LEAVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LEAVE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JComboBox<String> c;
    private javax.swing.JTextArea d;
    private javax.swing.JTextField e;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
